# Generated by Django 4.2.7 on 2024-10-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0002_subscription_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Traveler', 'Traveler'), ('Driver', 'Driver'), ('Admin', 'Admin')], default='Traveler', max_length=20),
        ),
    ]
