# Generated by Django 4.2.16 on 2024-10-16 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_number',
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_app.station')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='stations',
            field=models.ManyToManyField(related_name='stations_list', through='transport_app.RouteStation', to='transport_app.station'),
        ),
    ]
