# Generated by Django 4.2.16 on 2024-10-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0005_alter_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestation',
            name='time_from_start',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
