# Generated by Django 4.2.16 on 2024-10-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0006_routestation_time_from_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(default='0211362f-2992-4d43-8f16-9e37a673e02c', on_delete=django.db.models.deletion.CASCADE, to='transport_app.driver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_station', 'In Station'), ('left_station', 'Left Station')], max_length=20),
        ),
    ]
