# Generated by Django 4.2.16 on 2024-10-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0007_trip_driver_alter_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
